baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Green'
theme = 'green'

[author]
image = 'images/hero.png'
name = 'John Doe'
position = 'CEO'
description = "My primary responsibility is to lead and manage the company or organization I'm in charge of. I set strategic goals, oversee operations, and manage employees to ensure that we achieve our objectives. As a CEO, I also make financial decisions and represent the company to stakeholders such as investors, customers, and the public."
cv = 'https://example.org/cv.pdf'
